version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: https://outhkeeper-example.onrender.com/welcome
  allowed_return_urls:
    - https://outhkeeper-example.onrender.com
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: "179788582054-nsoebgquhqcnbq8ga0qf1inpkkrbt4tk.apps.googleusercontent.com"
            mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
            client_secret: ${GOOGLE_CLIENT_SECRET}
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            scope:
              - openid
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true

  flows:
    error:
      ui_url: https://outhkeeper-example.onrender.com/error

    settings:
      ui_url: https://outhkeeper-example.onrender.com/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://outhkeeper-example.onrender.com/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://outhkeeper-example.onrender.com/verification
      use: code
      after:
        default_browser_return_url: https://outhkeeper-example.onrender.com/welcome

    logout:
      after:
        default_browser_return_url: https://outhkeeper-example.onrender.com/login

    login:
      ui_url: https://outhkeeper-example.onrender.com/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://outhkeeper-example.onrender.com/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json


feature_flags:
  use_continue_with_transitions: true
